### ISSUE TITLE
TLS ALPN is "coap", not "coaps"

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-dtls-alpn#1]
Section 2 claims:

> For CoAP over TLS an ALPN ID was defined as "coaps" in [[RFC8323](https://www.ietf.org/archive/id/draft-ietf-core-coap-dtls-alpn-00.html#RFC8323)].

That is not true, please see 

https://www.rfc-editor.org/rfc/rfc8323.html#section-11.7
and
https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

**Comment by miri64** [comment]
Fixed in #2
